// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConnectivityClient is an autogenerated mock type for the ConnectivityClient type
type ConnectivityClient struct {
	mock.Mock
}

// GetCA provides a mock function with given fields:
func (_m *ConnectivityClient) GetCA() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewConnectivityClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewConnectivityClient creates a new instance of ConnectivityClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConnectivityClient(t mockConstructorTestingTNewConnectivityClient) *ConnectivityClient {
	mock := &ConnectivityClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
