run:
  modules-download-mode: readonly
  skip-dirs-use-default: true
  skip-files:
    - "mock.go|_test.go|fake_client.go"
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
    - gofmt
    - misspell
    - gochecknoinits
    - unparam
    - exportloopref
    - gosec
issues:
  exclude:
    # Check this issue for more info: https://github.com/kyoh86/scopelint/issues/4
    - Using the variable on range scope `tc` in function literal
  #TODO also needs a changed .golanci.yml as unused warning was skipped for this test
  exclude-rules:
    - path: 'mothership_integration_test.go'
      linters:
        - unused
    - text: "G404:" # Ignore weak random number generator lint. We do not need strong randomness here.
      linters:
        - gosec
