// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	pod "github.com/kyma-incubator/reconciler/pkg/reconciler/instances/istio/reset/pod"
	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// ExecuteAndWaitFor provides a mock function with given fields: _a0, _a1
func (_m *Handler) ExecuteAndWaitFor(_a0 context.Context, _a1 pod.CustomObject) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pod.CustomObject) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHandler(t mockConstructorTestingTNewHandler) *Handler {
	mock := &Handler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
