version: "3"
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
     - "8081:8080"
    volumes:
     - ./:/usr/share/nginx/html/docs
    environment:
     URL: /docs/internal_api.yaml
