// Package reconciler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package reconciler

// Defines values for Status.
const (
	StatusError Status = "error"

	StatusFailed Status = "failed"

	StatusNotstarted Status = "notstarted"

	StatusRunning Status = "running"

	StatusSuccess Status = "success"
)

// CallbackMessage defines model for callbackMessage.
type CallbackMessage struct {
	Error              string `json:"error"`
	ProcessingDuration int    `json:"processingDuration"`
	RetryID            string `json:"retryID"`
	Status             Status `json:"status"`
	Manifest           string `json:"manifest"`
}

// Status defines model for status.
type Status string

// PostOperationsSchedulingIDCallbackCorrelationIDJSONBody defines parameters for PostOperationsSchedulingIDCallbackCorrelationID.
type PostOperationsSchedulingIDCallbackCorrelationIDJSONBody CallbackMessage

// PostOperationsSchedulingIDCallbackCorrelationIDJSONRequestBody defines body for PostOperationsSchedulingIDCallbackCorrelationID for application/json ContentType.
type PostOperationsSchedulingIDCallbackCorrelationIDJSONRequestBody PostOperationsSchedulingIDCallbackCorrelationIDJSONBody
