// Code generated by reverse-kube-resource. DO NOT EDIT.

package scmigration

import v1unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

var (
	// Unstructured "service-catalog-addons-service-binding-usage-controller-cleanup"
	serviceCatalogAddonsServiceBindingUsageControllerCleanupUnstructuredJob = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "batch/v1",
			"kind":       "Job",
			"metadata": map[string]interface{}{
				"name":      "service-catalog-addons-service-binding-usage-controller-cleanup",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "service-catalog-addons-service-catalog-ui"
	serviceCatalogAddonsServiceCatalogUiUnstructuredPodSecurityPolicy = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "policy/v1beta1",
			"kind":       "PodSecurityPolicy",
			"metadata": map[string]interface{}{
				"name":      "service-catalog-addons-service-catalog-ui",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "service-catalog-addons-service-binding-usage-controller"
	serviceCatalogAddonsServiceBindingUsageControllerUnstructuredServiceAccount = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "v1",
			"kind":       "ServiceAccount",
			"metadata": map[string]interface{}{
				"name":      "service-catalog-addons-service-binding-usage-controller",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "service-catalog-addons-service-catalog-ui"
	serviceCatalogAddonsServiceCatalogUiUnstructuredServiceAccount = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "v1",
			"kind":       "ServiceAccount",
			"metadata": map[string]interface{}{
				"name":      "service-catalog-addons-service-catalog-ui",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "service-binding-usage-controller-process-sbu-spec"
	serviceBindingUsageControllerProcessSbuSpecUnstructuredConfigMap = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "v1",
			"kind":       "ConfigMap",
			"metadata": map[string]interface{}{
				"name":      "service-binding-usage-controller-process-sbu-spec",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "service-binding-usage-controller-dashboard"
	serviceBindingUsageControllerDashboardUnstructuredConfigMap = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "v1",
			"kind":       "ConfigMap",
			"metadata": map[string]interface{}{
				"name":      "service-binding-usage-controller-dashboard",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "service-catalog-ui"
	serviceCatalogUiUnstructuredConfigMap = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "v1",
			"kind":       "ConfigMap",
			"metadata": map[string]interface{}{
				"name":      "service-catalog-ui",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "service-catalog-addons-service-binding-usage-controller"
	serviceCatalogAddonsServiceBindingUsageControllerUnstructuredClusterRole = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "rbac.authorization.k8s.io/v1",
			"kind":       "ClusterRole",
			"metadata": map[string]interface{}{
				"name":      "service-catalog-addons-service-binding-usage-controller",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "service-catalog-addons-service-binding-usage-controller"
	serviceCatalogAddonsServiceBindingUsageControllerUnstructuredClusterRoleBinding = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "rbac.authorization.k8s.io/v1",
			"kind":       "ClusterRoleBinding",
			"metadata": map[string]interface{}{
				"name":      "service-catalog-addons-service-binding-usage-controller",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "service-catalog-addons-service-catalog-ui"
	serviceCatalogAddonsServiceCatalogUiUnstructuredRole = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "rbac.authorization.k8s.io/v1",
			"kind":       "Role",
			"metadata": map[string]interface{}{
				"name":      "service-catalog-addons-service-catalog-ui",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "service-catalog-addons-service-catalog-ui"
	serviceCatalogAddonsServiceCatalogUiUnstructuredRoleBinding = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "rbac.authorization.k8s.io/v1",
			"kind":       "RoleBinding",
			"metadata": map[string]interface{}{
				"name":      "service-catalog-addons-service-catalog-ui",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "service-catalog-addons-service-binding-usage-controller"
	serviceCatalogAddonsServiceBindingUsageControllerUnstructuredService = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "v1",
			"kind":       "Service",
			"metadata": map[string]interface{}{
				"name":      "service-catalog-addons-service-binding-usage-controller",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "service-catalog-addons-service-catalog-ui"
	serviceCatalogAddonsServiceCatalogUiUnstructuredService = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "v1",
			"kind":       "Service",
			"metadata": map[string]interface{}{
				"name":      "service-catalog-addons-service-catalog-ui",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "service-catalog-addons-service-binding-usage-controller"
	serviceCatalogAddonsServiceBindingUsageControllerUnstructuredDeployment = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "apps/v1",
			"kind":       "Deployment",
			"metadata": map[string]interface{}{
				"name":      "service-catalog-addons-service-binding-usage-controller",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "service-catalog-addons-service-catalog-ui"
	serviceCatalogAddonsServiceCatalogUiUnstructuredDeployment = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "apps/v1",
			"kind":       "Deployment",
			"metadata": map[string]interface{}{
				"name":      "service-catalog-addons-service-catalog-ui",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "service-catalog-addons-service-catalog-ui"
	serviceCatalogAddonsServiceCatalogUiUnstructuredDestinationRule = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "networking.istio.io/v1alpha3",
			"kind":       "DestinationRule",
			"metadata": map[string]interface{}{
				"name":      "service-catalog-addons-service-catalog-ui",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "service-catalog-addons-service-binding-usage-controller"
	serviceCatalogAddonsServiceBindingUsageControllerUnstructuredPeerAuthentication = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "security.istio.io/v1beta1",
			"kind":       "PeerAuthentication",
			"metadata": map[string]interface{}{
				"name":      "service-catalog-addons-service-binding-usage-controller",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "service-catalog-addons-service-binding-usage-controller"
	serviceCatalogAddonsServiceBindingUsageControllerUnstructuredServiceMonitor = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "monitoring.coreos.com/v1",
			"kind":       "ServiceMonitor",
			"metadata": map[string]interface{}{
				"name":      "service-catalog-addons-service-binding-usage-controller",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "deployment"
	deploymentUnstructuredUsageKind = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "servicecatalog.kyma-project.io/v1alpha1",
			"kind":       "UsageKind",
			"metadata": map[string]interface{}{
				"name":      "deployment",
				"namespace": "kyma-system",
			},
		},
	}

	// Unstructured "service-catalog-addons-service-catalog-ui-catalog"
	serviceCatalogAddonsServiceCatalogUiCatalogUnstructuredVirtualService = v1unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "networking.istio.io/v1alpha3",
			"kind":       "VirtualService",
			"metadata": map[string]interface{}{
				"name":      "service-catalog-addons-service-catalog-ui-catalog",
				"namespace": "kyma-system",
			},
		},
	}
)
