// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ExternalComponentAuthenticator is an autogenerated mock type for the ExternalComponentAuthenticator type
type ExternalComponentAuthenticator struct {
	mock.Mock
}

// Do provides a mock function with given fields: r
func (_m *ExternalComponentAuthenticator) Do(r *http.Request) error {
	ret := _m.Called(r)

	var r0 error
	if rf, ok := ret.Get(0).(func(*http.Request) error); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewExternalComponentAuthenticator interface {
	mock.TestingT
	Cleanup(func())
}

// NewExternalComponentAuthenticator creates a new instance of ExternalComponentAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExternalComponentAuthenticator(t mockConstructorTestingTNewExternalComponentAuthenticator) *ExternalComponentAuthenticator {
	mock := &ExternalComponentAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
