// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	chart "github.com/kyma-incubator/reconciler/pkg/reconciler/chart"
	mock "github.com/stretchr/testify/mock"
)

// Factory is an autogenerated mock type for the Factory type
type Factory struct {
	mock.Mock
}

// Delete provides a mock function with given fields: version
func (_m *Factory) Delete(version string) error {
	ret := _m.Called(version)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: version
func (_m *Factory) Get(version string) (*chart.KymaWorkspace, error) {
	ret := _m.Called(version)

	var r0 *chart.KymaWorkspace
	if rf, ok := ret.Get(0).(func(string) *chart.KymaWorkspace); ok {
		r0 = rf(version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chart.KymaWorkspace)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExternalComponent provides a mock function with given fields: component
func (_m *Factory) GetExternalComponent(component *chart.Component) (*chart.Workspace, error) {
	ret := _m.Called(component)

	var r0 *chart.Workspace
	if rf, ok := ret.Get(0).(func(*chart.Component) *chart.Workspace); ok {
		r0 = rf(component)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chart.Workspace)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*chart.Component) error); ok {
		r1 = rf(component)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
