DROP INDEX public.inventory_cluster_config_statuses__idx_deleted_id_status_created;
DROP INDEX public.inventory_cluster_config_statuses__idx_cluster_version_id;
DROP INDEX public.inventory_cluster_configs__idx_deleted_kyma_version_cluster_version_created;
DROP INDEX public.inventory_cluster_configs__idx_cluster_version_version;
DROP INDEX public.inventory_cluster__idx_deleted_runtime_id;