apiVersion: v1
kind: ConfigMap
metadata:
  name: mothership-reconciler
data:
  component-reconcilers.json: |-
    {
    {{- include "mothership-reconciler.component-reconcilers" . | trimAll "," | nindent 6 }}
    }
---
