apiVersion: v1
kind: ConfigMap
metadata:
  name: component-reconcilers
  namespace: {{ .Release.Namespace }}
data:
  component-reconcilers.json: |-
    {
    {{- include "mothership-reconciler.component-reconcilers" . | trimAll "," | nindent 6 }}
    }
---
