apiVersion: v1
kind: ConfigMap
metadata:
  name: mothership-reconciler
  namespace: {{ .Release.Namespace }}
data:
  reconciler.yaml: |-
    db:
      driver: postgres
      encryption:
        keyFile: "/encryption/db-encryption.key"
      blockQueries: true
      postgres:
        host: "localhost"
        database: "kyma"
        port: 5432
        user: kyma
        password: kyma
        useSsl: false
      sqlite:
        file: "reconciler.db"
        deploySchema: true
        resetDatabase: false
    mothership:
      scheme: {{ .Values.service.scheme }}
      host: {{ include "mothership-reconciler.fullname" . }}
      port: {{ .Values.service.port }}
      scheduler:
        reconcilers:
          {{- range $component := .Values.global.components }}
          {{ $component }}:
            url: http://{{ $component }}-reconciler:8080/v1/run
          {{- end }}
        {{- if .Values.preComponents }}
        preComponents:
{{ toYaml .Values.preComponents | indent 10 }}
        {{- end }}
---
