// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	istioctl "github.com/kyma-incubator/reconciler/pkg/reconciler/instances/istio/istioctl"
	mock "github.com/stretchr/testify/mock"
)

// VersionChecker is an autogenerated mock type for the VersionChecker type
type VersionChecker struct {
	mock.Mock
}

// GetIstioVersion provides a mock function with given fields: pathToBinary
func (_m *VersionChecker) GetIstioVersion(pathToBinary string) (istioctl.Version, error) {
	ret := _m.Called(pathToBinary)

	var r0 istioctl.Version
	if rf, ok := ret.Get(0).(func(string) istioctl.Version); ok {
		r0 = rf(pathToBinary)
	} else {
		r0 = ret.Get(0).(istioctl.Version)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pathToBinary)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
