// Code generated by mockery v2.1.0. DO NOT EDIT.

package mocks

import (
	service "github.com/kyma-incubator/reconciler/pkg/reconciler/service"
	mock "github.com/stretchr/testify/mock"
)

// Action is an autogenerated mock type for the Action type
type Action struct {
	mock.Mock
}

// Run provides a mock function with given fields: helper
func (_m *Action) Run(helper *service.ActionContext) error {
	ret := _m.Called(helper)

	var r0 error
	if rf, ok := ret.Get(0).(func(*service.ActionContext) error); ok {
		r0 = rf(helper)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
