// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	chart "github.com/kyma-incubator/reconciler/pkg/reconciler/chart"

	kubernetes "github.com/kyma-incubator/reconciler/pkg/reconciler/kubernetes"

	mock "github.com/stretchr/testify/mock"

	reconciler "github.com/kyma-incubator/reconciler/pkg/reconciler"
)

// Operation is an autogenerated mock type for the Operation type
type Operation struct {
	mock.Mock
}

// Invoke provides a mock function with given fields: ctx, chartProvider, model, kubeClient
func (_m *Operation) Invoke(ctx context.Context, chartProvider chart.Provider, model *reconciler.Task, kubeClient kubernetes.Client) error {
	ret := _m.Called(ctx, chartProvider, model, kubeClient)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, chart.Provider, *reconciler.Task, kubernetes.Client) error); ok {
		r0 = rf(ctx, chartProvider, model, kubeClient)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
