// Code generated by mockery (devel). DO NOT EDIT.

package connectivityproxymocks

import (
	chart "github.com/kyma-incubator/reconciler/pkg/reconciler/chart"

	mock "github.com/stretchr/testify/mock"
)

// ChartProvider is an autogenerated mock type for the ChartProvider type
type ChartProvider struct {
	mock.Mock
}

// RenderManifest provides a mock function with given fields: component
func (_m *ChartProvider) RenderManifest(component *chart.Component) (*chart.Manifest, error) {
	ret := _m.Called(component)

	var r0 *chart.Manifest
	if rf, ok := ret.Get(0).(func(*chart.Component) *chart.Manifest); ok {
		r0 = rf(component)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chart.Manifest)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*chart.Component) error); ok {
		r1 = rf(component)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
