// Code generated by mockery 2.7.4. DO NOT EDIT.

package scheduler

import mock "github.com/stretchr/testify/mock"

// MockWorkerFactory is an autogenerated mock type for the WorkerFactory type
type MockWorkerFactory struct {
	mock.Mock
}

// ForComponent provides a mock function with given fields: component
func (_m *MockWorkerFactory) ForComponent(component string) (ReconciliationWorker, error) {
	ret := _m.Called(component)

	var r0 ReconciliationWorker
	if rf, ok := ret.Get(0).(func(string) ReconciliationWorker); ok {
		r0 = rf(component)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ReconciliationWorker)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(component)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
