// Code generated by mockery 2.7.4. DO NOT EDIT.

package scheduler

import (
	cluster "github.com/kyma-incubator/reconciler/pkg/cluster"
	keb "github.com/kyma-incubator/reconciler/pkg/keb"

	mock "github.com/stretchr/testify/mock"
)

// MockReconciliationWorker is an autogenerated mock type for the ReconciliationWorker type
type MockReconciliationWorker struct {
	mock.Mock
}

// Reconcile provides a mock function with given fields: component, state, schedulingID, installCRD
func (_m *MockReconciliationWorker) Reconcile(component *keb.Component, state cluster.State, schedulingID string, installCRD bool) error {
	ret := _m.Called(component, state, schedulingID, installCRD)

	var r0 error
	if rf, ok := ret.Get(0).(func(*keb.Component, cluster.State, string, bool) error); ok {
		r0 = rf(component, state, schedulingID, installCRD)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
