// Code generated by mockery 2.7.4. DO NOT EDIT.

package scheduler

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockInventoryWatcher is an autogenerated mock type for the InventoryWatcher type
type MockInventoryWatcher struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, informer
func (_m *MockInventoryWatcher) Run(ctx context.Context, informer InventoryQueue) error {
	ret := _m.Called(ctx, informer)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, InventoryQueue) error); ok {
		r0 = rf(ctx, informer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
