// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	istioctl "github.com/kyma-incubator/reconciler/pkg/reconciler/instances/istio/istioctl"
	mock "github.com/stretchr/testify/mock"
)

// ExecutableResolver is an autogenerated mock type for the ExecutableResolver type
type ExecutableResolver struct {
	mock.Mock
}

// FindIstioctl provides a mock function with given fields: version
func (_m *ExecutableResolver) FindIstioctl(version istioctl.Version) (*istioctl.Executable, error) {
	ret := _m.Called(version)

	var r0 *istioctl.Executable
	if rf, ok := ret.Get(0).(func(istioctl.Version) *istioctl.Executable); ok {
		r0 = rf(version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*istioctl.Executable)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(istioctl.Version) error); ok {
		r1 = rf(version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewExecutableResolver interface {
	mock.TestingT
	Cleanup(func())
}

// NewExecutableResolver creates a new instance of ExecutableResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExecutableResolver(t mockConstructorTestingTNewExecutableResolver) *ExecutableResolver {
	mock := &ExecutableResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
