// Code generated by mockery v2.9.4. DO NOT EDIT.

package mock

import (
	context "context"

	kubernetes "k8s.io/client-go/kubernetes"

	mock "github.com/stretchr/testify/mock"

	zap "go.uber.org/zap"
)

// Hydra is an autogenerated mock type for the Hydra type
type Hydra struct {
	mock.Mock
}

// TriggerSynchronization provides a mock function with given fields: _a0, client, logger, namespace
func (_m *Hydra) TriggerSynchronization(_a0 context.Context, client kubernetes.Interface, logger *zap.SugaredLogger, namespace string) error {
	ret := _m.Called(_a0, client, logger, namespace)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, kubernetes.Interface, *zap.SugaredLogger, string) error); ok {
		r0 = rf(_a0, client, logger, namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
