// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	kubernetes "k8s.io/client-go/kubernetes"

	retry "github.com/avast/retry-go"

	v1 "k8s.io/api/core/v1"

	zap "go.uber.org/zap"
)

// Action is an autogenerated mock type for the Action type
type Action struct {
	mock.Mock
}

// Reset provides a mock function with given fields: kubeClient, retryOpts, podsList, log, debug
func (_m *Action) Reset(kubeClient kubernetes.Interface, retryOpts []retry.Option, podsList v1.PodList, log *zap.SugaredLogger, debug bool) {
	_m.Called(kubeClient, retryOpts, podsList, log, debug)
}
