// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/api/core/v1"
)

// Action is an autogenerated mock type for the Action type
type Action struct {
	mock.Mock
}

// Reset provides a mock function with given fields: podsList
func (_m *Action) Reset(podsList v1.PodList) {
	_m.Called(podsList)
}
