// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	kubernetes "k8s.io/client-go/kubernetes"

	pod "github.com/kyma-incubator/reconciler/pkg/reconciler/instances/istio/reset/pod"

	retry "github.com/avast/retry-go"

	v1 "k8s.io/api/core/v1"

	zap "go.uber.org/zap"
)

// Action is an autogenerated mock type for the Action type
type Action struct {
	mock.Mock
}

// Reset provides a mock function with given fields: kubeClient, retryOpts, podsList, log, debug, waitOpts
func (_m *Action) Reset(kubeClient kubernetes.Interface, retryOpts []retry.Option, podsList v1.PodList, log *zap.SugaredLogger, debug bool, waitOpts pod.WaitOptions) error {
	ret := _m.Called(kubeClient, retryOpts, podsList, log, debug, waitOpts)

	var r0 error
	if rf, ok := ret.Get(0).(func(kubernetes.Interface, []retry.Option, v1.PodList, *zap.SugaredLogger, bool, pod.WaitOptions) error); ok {
		r0 = rf(kubeClient, retryOpts, podsList, log, debug, waitOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
