// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/api/core/v1"
)

// ResetAction is an autogenerated mock type for the ResetAction type
type ResetAction struct {
	mock.Mock
}

// Reset provides a mock function with given fields: podsList
func (_m *ResetAction) Reset(podsList v1.PodList) {
	_m.Called(podsList)
}
