// Code generated by mockery v2.9.4. DO NOT EDIT.

package mock

import (
	context "context"

	kubernetes "github.com/kyma-incubator/reconciler/pkg/reconciler/kubernetes"

	mock "github.com/stretchr/testify/mock"

	zap "go.uber.org/zap"
)

// RolloutHandler is an autogenerated mock type for the RolloutHandler type
type RolloutHandler struct {
	mock.Mock
}

// RolloutAndWaitForDeployment provides a mock function with given fields: ctx, deployment, namespace, client, logger
func (_m *RolloutHandler) RolloutAndWaitForDeployment(ctx context.Context, deployment string, namespace string, client kubernetes.Client, logger *zap.SugaredLogger) error {
	ret := _m.Called(ctx, deployment, namespace, client, logger)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, kubernetes.Client, *zap.SugaredLogger) error); ok {
		r0 = rf(ctx, deployment, namespace, client, logger)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
