// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	components "github.com/kyma-incubator/reconciler/internal/components"
	mock "github.com/stretchr/testify/mock"

	workspace "github.com/kyma-incubator/reconciler/pkg/reconciler/workspace"
)

// Factory is an autogenerated mock type for the Factory type
type Factory struct {
	mock.Mock
}

// Delete provides a mock function with given fields: version
func (_m *Factory) Delete(version string) error {
	ret := _m.Called(version)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: version, component
func (_m *Factory) Get(version string, component ...*components.Component) (*workspace.Workspace, error) {
	_va := make([]interface{}, len(component))
	for _i := range component {
		_va[_i] = component[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, version)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *workspace.Workspace
	if rf, ok := ret.Get(0).(func(string, ...*components.Component) *workspace.Workspace); ok {
		r0 = rf(version, component...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workspace.Workspace)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, ...*components.Component) error); ok {
		r1 = rf(version, component...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
