run:
  modules-download-mode: readonly
issues:
  exclude:
    # Check this issue for more info: https://github.com/kyoh86/scopelint/issues/4
    - Using the variable on range scope `tc` in function literal
  #TODO also needs a changed .golanci.yml as unused warning was skipped for this test
  exclude-rules:
    - path: 'mothership_integration_test.go'
      linters:
        - unused
    - text: "G404:" # Ignore weak random number generator lint. We do not need strong randomness here.
      linters:
        - gosec
linters:
  disable:
    - staticcheck
