# This file is not part of official PostgreSQL chart
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-db-init
  namespace: {{ .Release.Namespace }}
data:
  init-reconciler-db.sql: |
    CREATE DATABASE kyma;
