apiVersion: v1
kind: Secret
metadata:
  name: reconciler-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  annotations:
    "helm.sh/hook": "pre-install" # Modified
    "helm.sh/hook-delete-policy": "before-hook-creation" # Modified
type: Opaque
data:
  postgresql-serviceName: {{ include "postgresql.fullname" . | b64enc | quote }} # Modified
  postgresql-servicePort: {{ include "postgresql.port" . | b64enc | quote }} # Modified
  postgresql-sslMode: {{ "disable" | b64enc | quote }}
