{{ $global := . }}
{{- range $component := .Values.global.components }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kyma-project.io/component-reconciler: ""
    component: {{ $component }}
  name: {{ $component }}-reconciler
  namespace: {{ $global.Release.Namespace }}
spec:
  selector:
    matchLabels:
      kyma-project.io/component-reconciler: ""
      component: {{ $component }}
  replicas: 1
  template:
    metadata:
      labels:
        kyma-project.io/component-reconciler: ""
        component: {{ $component }}
    spec:
      containers:
      - image: "{{ $global.Values.global.image.repository }}:{{ $global.Values.global.image.tag }}"
        imagePullPolicy: {{ $global.Values.global.image.pullPolicy }}
        args:
          - reconciler
          - reconciler
          - start
          - {{ $component }}
        name: reconciler
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources: {}
      securityContext:
        runAsUser: 2000
---
{{- end }}
