{{ $global := . }}
{{- range $component := .Values.global.components }}
apiVersion: v1
kind: Service
metadata:
  name: component-reconcilers-{{ $component }}
  namespace: {{ $global.Release.Namespace }}
  labels:
    name: component-reconcilers-{{ $component }}
    component: {{ $component }}
spec:
  type: {{ $global.Values.service.type }}
  ports:
    - port: {{ $global.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: component-reconcilers-{{ $component }}
    component: {{ $component }}
---
{{- end }}
