// Code generated by mockery 2.9.4. DO NOT EDIT.

package mock

import (
	actions "github.com/kyma-incubator/reconciler/pkg/reconciler/instances/istio/actions"
	istioctl "github.com/kyma-incubator/reconciler/pkg/reconciler/instances/istio/istioctl"

	kubernetes "github.com/kyma-incubator/reconciler/pkg/reconciler/kubernetes"

	mock "github.com/stretchr/testify/mock"

	workspace "github.com/kyma-incubator/reconciler/pkg/reconciler/workspace"

	zap "go.uber.org/zap"
)

// IstioPerformer is an autogenerated mock type for the IstioPerformer type
type IstioPerformer struct {
	mock.Mock
}

// Install provides a mock function with given fields: kubeConfig, manifest, logger, commander
func (_m *IstioPerformer) Install(kubeConfig string, manifest string, logger *zap.SugaredLogger, commander istioctl.Commander) error {
	ret := _m.Called(kubeConfig, manifest, logger, commander)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, *zap.SugaredLogger, istioctl.Commander) error); ok {
		r0 = rf(kubeConfig, manifest, logger, commander)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PatchMutatingWebhook provides a mock function with given fields: kubeClient, logger
func (_m *IstioPerformer) PatchMutatingWebhook(kubeClient kubernetes.Client, logger *zap.SugaredLogger) error {
	ret := _m.Called(kubeClient, logger)

	var r0 error
	if rf, ok := ret.Get(0).(func(kubernetes.Client, *zap.SugaredLogger) error); ok {
		r0 = rf(kubeClient, logger)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: kubeConfig, manifest, logger, commander
func (_m *IstioPerformer) Update(kubeConfig string, manifest string, logger *zap.SugaredLogger, commander istioctl.Commander) error {
	ret := _m.Called(kubeConfig, manifest, logger, commander)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, *zap.SugaredLogger, istioctl.Commander) error); ok {
		r0 = rf(kubeConfig, manifest, logger, commander)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Version provides a mock function with given fields: _a0, branchVersion, istioChart, kubeConfig, logger, commander
func (_m *IstioPerformer) Version(_a0 workspace.Factory, branchVersion string, istioChart string, kubeConfig string, logger *zap.SugaredLogger, commander istioctl.Commander) (actions.IstioVersion, error) {
	ret := _m.Called(_a0, branchVersion, istioChart, kubeConfig, logger, commander)

	var r0 actions.IstioVersion
	if rf, ok := ret.Get(0).(func(workspace.Factory, string, string, string, *zap.SugaredLogger, istioctl.Commander) actions.IstioVersion); ok {
		r0 = rf(_a0, branchVersion, istioChart, kubeConfig, logger, commander)
	} else {
		r0 = ret.Get(0).(actions.IstioVersion)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(workspace.Factory, string, string, string, *zap.SugaredLogger, istioctl.Commander) error); ok {
		r1 = rf(_a0, branchVersion, istioChart, kubeConfig, logger, commander)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
