apiVersion: v1
kind: Pod
metadata:
  labels:
  {{- include "reconciler.labels" . | nindent 4 }}
  name: reconciler
spec:
  containers:
  - image: rafaljankowski/reconciler:v1
    args:
      - reconciler
      - service
      - start
    name: reconciler
    ports:
    - name: http
      containerPort: 8080
      protocol: TCP
    resources: {}
    env:
      - name: RECONCILER_DATABASE_USER
        valueFrom:
          secretKeyRef:
            name: reconciler-postgresql
            key: postgresql-reconciler-username
      - name: RECONCILER_DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: reconciler-postgresql
            key: postgresql-reconciler-password
      - name: RECONCILER_DATABASE_HOST
        valueFrom:
          secretKeyRef:
            name: reconciler-postgresql
            key: postgresql-serviceName
      - name: RECONCILER_DATABASE_PORT
        valueFrom:
          secretKeyRef:
            name: reconciler-postgresql
            key: postgresql-servicePort
      - name: RECONCILER_DATABASE_NAME
        valueFrom:
          secretKeyRef:
            name: reconciler-postgresql
            key: postgresql-reconciler-db-name
  dnsPolicy: ClusterFirst
  restartPolicy: Always
