apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "fullname" . }}
spec:
  gateways:
  - bookinfo-gateway
  hosts:
  - "*"
  http:
  - match:
      - uri:
          exact: /v1/clusters
    route:
      - destination:
          host: reconciler
          port:
            number: 80
{{/*  - corsPolicy:*/}}
{{/*      allowHeaders:*/}}
{{/*      - Authorization*/}}
{{/*      - Content-Type*/}}
{{/*      - X-Broker-API-Version*/}}
{{/*      allowMethods: ["GET", "PUT", "DELETE"]*/}}
{{/*      allowOrigins:*/}}
{{/*      - regex: ".*"*/}}
{{/*    match:*/}}
{{/*    - uri:*/}}
{{/*        regex: /oauth/([^/]+/)?v2/.**/}}
{{/*    route:*/}}
{{/*    - destination:*/}}
{{/*        host: {{ .Values.global.oathkeeper.host }}*/}}
{{/*        port:*/}}
{{/*          number: {{ .Values.global.oathkeeper.port }}*/}}
{{/*  - corsPolicy:*/}}
{{/*      allowHeaders:*/}}
{{/*      - Authorization*/}}
{{/*      - Content-Type*/}}
{{/*      allowMethods: ["GET"]*/}}
{{/*      allowOrigins:*/}}
{{/*      - regex: ".*"*/}}
{{/*    match:*/}}
{{/*    - uri:*/}}
{{/*        regex: /v1/clusters/.**/}}
{{/*    route:*/}}
{{/*    - destination:*/}}
{{/*        host: {{ .Values.global.oathkeeper.host }}*/}}
{{/*        port:*/}}
{{/*          number: {{ .Values.global.oathkeeper.port }}*/}}
