// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	zap "go.uber.org/zap"
)

// CmdExecutor is an autogenerated mock type for the CmdExecutor type
type CmdExecutor struct {
	mock.Mock
}

// RuntWithRetry provides a mock function with given fields: logger, command, args
func (_m *CmdExecutor) RuntWithRetry(logger *zap.SugaredLogger, command string, args ...string) error {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, logger, command)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(*zap.SugaredLogger, string, ...string) error); ok {
		r0 = rf(logger, command, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
