<<<<<<< HEAD
<<<<<<< HEAD
// Code generated by mockery v2.9.4. DO NOT EDIT.
=======
// Code generated by mockery 2.9.0. DO NOT EDIT.
>>>>>>> f96dea9 (Wait for Istio proxies after Reset)
=======
// Code generated by mockery 2.7.5. DO NOT EDIT.
>>>>>>> c7aacff (Fix tests and rework configuration of Istio Reset)

package mocks

import (
	config "github.com/kyma-incubator/reconciler/pkg/reconciler/instances/istio/reset/config"
	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/api/core/v1"
)

// IstioProxyReset is an autogenerated mock type for the IstioProxyReset type
type IstioProxyReset struct {
	mock.Mock
}

// Run provides a mock function with given fields: cfg
func (_m *IstioProxyReset) Run(cfg config.IstioProxyConfig) error {
	ret := _m.Called(cfg)

	var r0 error
	if rf, ok := ret.Get(0).(func(config.IstioProxyConfig) error); ok {
		r0 = rf(cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WaitUntilProxiesReady provides a mock function with given fields: podsList, cfg
func (_m *IstioProxyReset) WaitUntilProxiesReady(podsList v1.PodList, cfg config.IstioProxyConfig) error {
	ret := _m.Called(podsList, cfg)

	var r0 error
	if rf, ok := ret.Get(0).(func(v1.PodList, config.IstioProxyConfig) error); ok {
		r0 = rf(podsList, cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
