// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	config "github.com/kyma-incubator/reconciler/pkg/reconciler/instances/istio/reset/config"
	mock "github.com/stretchr/testify/mock"
)

// IstioProxyReset is an autogenerated mock type for the IstioProxyReset type
type IstioProxyReset struct {
	mock.Mock
}

// Run provides a mock function with given fields: cfg
func (_m *IstioProxyReset) Run(cfg config.IstioProxyConfig) error {
	ret := _m.Called(cfg)

	var r0 error
	if rf, ok := ret.Get(0).(func(config.IstioProxyConfig) error); ok {
		r0 = rf(cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIstioProxyReset interface {
	mock.TestingT
	Cleanup(func())
}

// NewIstioProxyReset creates a new instance of IstioProxyReset. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIstioProxyReset(t mockConstructorTestingTNewIstioProxyReset) *IstioProxyReset {
	mock := &IstioProxyReset{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
