// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	kubernetes "k8s.io/client-go/kubernetes"

	pod "github.com/kyma-incubator/reconciler/pkg/reconciler/instances/istio/reset/pod"

	retry "github.com/avast/retry-go"

	v1 "k8s.io/api/core/v1"

	zap "go.uber.org/zap"
)

// Matcher is an autogenerated mock type for the Matcher type
type Matcher struct {
	mock.Mock
}

// GetHandlersMap provides a mock function with given fields: kubeClient, retryOpts, podsList, log, debug
func (_m *Matcher) GetHandlersMap(kubeClient kubernetes.Interface, retryOpts []retry.Option, podsList v1.PodList, log *zap.SugaredLogger, debug bool) map[pod.Handler][]pod.CustomObject {
	ret := _m.Called(kubeClient, retryOpts, podsList, log, debug)

	var r0 map[pod.Handler][]pod.CustomObject
	if rf, ok := ret.Get(0).(func(kubernetes.Interface, []retry.Option, v1.PodList, *zap.SugaredLogger, bool) map[pod.Handler][]pod.CustomObject); ok {
		r0 = rf(kubeClient, retryOpts, podsList, log, debug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[pod.Handler][]pod.CustomObject)
		}
	}

	return r0
}
