// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	pod "github.com/kyma-incubator/reconciler/pkg/reconciler/instances/istio/reset/pod"
	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/api/core/v1"
)

// Matcher is an autogenerated mock type for the Matcher type
type Matcher struct {
	mock.Mock
}

// GetHandlersMap provides a mock function with given fields: _a0
func (_m *Matcher) GetHandlersMap(_a0 v1.PodList) map[pod.Handler][]pod.CustomObject {
	ret := _m.Called(_a0)

	var r0 map[pod.Handler][]pod.CustomObject
	if rf, ok := ret.Get(0).(func(v1.PodList) map[pod.Handler][]pod.CustomObject); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[pod.Handler][]pod.CustomObject)
		}
	}

	return r0
}
